export * from "./add";
export * from "./decrement";
export * from "./divide";
export * from "./increment";
export * from "./is-even";
export * from "./is-odd";
export * from "./multiply";
export * from "./subtract";
export * from "./to-list";
